from enum import Enum


class StatusCodes(Enum):
    # Messaging
    REQUEST_SEND_MESSAGE = 100
    REQUEST_GET_UNSENT_MESSAGES = 101
    MESSAGE_DELIVERED = 210
    MESSAGE_NOT_DELIVERED = 1001
    MESSAGE_SAVED = 212

    # Registration Workflow
    REQUEST_REGISTRATION_TOKEN = 200
    REQUEST_SECURE_REGISTRATION_INIT = 201
    TOKEN_ISSUED = 202
    REQUEST_SECURE_REGISTRATION_COMPLETE = 203
    REQUEST_REGISTRATION_COMPLETE = 204

    # Errors and General
    SERVER_ERROR = 1003
    INVALID_TOKEN = 1004
    REGISTRATION_FAILED = 1005
